### PR TITLE
TMS Bar FindModules bugfix

### PR DESCRIPTION
**Pull request by jdkio**
In testing Tejin's file
ConvertToTMSTree.exe /dune/app/users/tejinc/DUNESoftware/ND/work/edep_files/larsoft_edep_dump_tms_merged.root
the code got stuck in an infinite loop. Turns out it's because the hit was from a geometry node above volDetEnclosure. So the nodes travel up to volWorld and then gets stuck in an infinite loop there. This bugfix prevents that.

### CODE REVIEW

**Comment by jdkio** [comment]
I'm not sure why the timing commits made it in. It's supposed to only be the last commit.

**Comment by LiamOS** [comment]
Would it be possible to submit another request with only the correct commit? I don't think I'm able to remove them with the web interface.

**Comment by ast0815** [comment]
You can rebase and force-push on this PR. No need for a new one.

**Comment by jdkio** [comment]
I made things much worse by trying to rebase. I need to figure this out, sorry

**Review by LiamOS — APPROVED** [review]
Resolved and merged.

**Pull request merged**
