### PR TITLE
added SL7 compatible setup file with UPS

### PR DESCRIPTION
**Pull request by LiamOS**
Final version of setup.sh before I -'d it. If you want anything changed let me know or push to this branch.

### CODE REVIEW

**Comment by jdkio** [comment]
This works. ProcessND.py assumes the script is called `setup.sh` so I added that to my current branch

**Comment by LiamOS** [comment]
Will change to setup.sh tomorrow and add a check on `/etc/redhat-release ` or whatever the file is, if it's A9 I can make it source the _FNAL one.

**Review by jdkio — APPROVED** [review]
Sorry, I left this PR hanging. I like that this checks the os version. It should work on the grid as well, right? Or will the grid give away that it's AL9 running an SL7 container? I'm not 100% sure but it's probably fine

**Comment by LiamOS** [comment]
If run inside an SL7 container the container will present its own /etc/redhat-release, and report SL7.
Can merge that change later if you like, it was mostly for your use anyway since at that point in time I though we were mere weeks away from DUNE being fully spackified.

**Comment by LiamOS** [comment]
Closing this, the relevant changes have made their way onto main through edits of Jeffrey's setup.sh. setup_FNAL.sh has been the default for users working on the GPVMs for some time.

**Pull request closed without merging**
