### PR TITLE
125 potential problem with tracks in clusters

### PR DESCRIPTION
**Pull request by AsaNehm**
- Some bug fixes in the 3D track matching
- Pre-clustering is added in as turn-on/off option in config file
- Used extrapolation for back-extension of tracks into pre-clusters
- Also altered the simple track matching condition

### CODE REVIEW

**Comment by jdkio** [comment]
I'm trying to draw some comparisons to main to see if we can see a change. Would you please run the three files from [the validation page](https://github.com/DUNE/dune-tms/wiki/Validating-Changes) and save them somewhere

I tried compiling it myself, but I get 
```
TMS_Reco.cpp: In member function ‘std::vector<TMS_Track> TMS_TrackFinder::TrackMatching3D()’:
TMS_Reco.cpp:1624:29: error: ‘ChargeID’ was not declared in this scope
 1624 |             aTrack.Charge = ChargeID.ID_Track_Charge(aTrack.Hits);
      |                             ^~~~~~~~
```

Recreate:
```
git clone git@github.com:DUNE/dune-tms.git
cd dune-tms
. setup_FNAL.sh
git checkout 125-potential-problem-with-tracks-in-clusters
make clean & make
# Get TMS_Reco.cpp:1624:29: error: 'ChargeID' was not declared in this scope
```
I'm not sure why the checks aren't seeing it

**Comment by jdkio** [comment]
One issue seems to be that my local copy (and the branch copy) doesn't have `TMS_ChargeID.cpp` while the git build does:
> g++ -c -Wall -Wextra -g -fPIC -O3 -pthread -std=c++17 -m64 -I/home/runner/work/dune-tms/root/include -I/home/runner/work/dune-tms/edep-sim/Linux/include -I/home/runner/work/dune-tms/Geant4-10.7.4-Linux/bin/../include/ -I/home/runner/work/dune-tms/Geant4-10.7.4-Linux/include/Geant4 -I../toml11/ TMS_ChargeID.cpp

See [log here](https://github.com/DUNE/dune-tms/actions/runs/10596697058/job/29365214522?pr=135). I also see some long toml warning that isn't present in my local compilation. @LiamOS, do you know why this is happening?

**Comment by AsaNehm** [comment]
An explanation could be that I created this branch from another branch of mine where the charge ID was not implemented yet and therefore on both branches the TMS_ChargeID files doesn't really exist...

**Comment by LiamOS** [comment]
> > g++ -c -Wall -Wextra -g -fPIC -O3 -pthread -std=c++17 -m64 -I/home/runner/work/dune-tms/root/include -I/home/runner/work/dune-tms/edep-sim/Linux/include -I/home/runner/work/dune-tms/Geant4-10.7.4-Linux/bin/../include/ -I/home/runner/work/dune-tms/Geant4-10.7.4-Linux/include/Geant4 -I../toml11/ TMS_ChargeID.cpp
> 
> See [log here](https://github.com/DUNE/dune-tms/actions/runs/10596697058/job/29365214522?pr=135). I also see some long toml warning that isn't present in my local compilation. @LiamOS, do you know why this is happening?

The TOML warnings are GCC version dependent I think, I didn't dive too deep into it but from my few minutes on stackoverflow my impression was that GCC 12 produced this warning spuriously in cases it shouldn't.

I can throw -Wfree-nonheap-object into the CFLAGS if you like, it'll probably be a few years before GCC 12 becomes a rarity.

**Comment by jdkio** [comment]
@AsaNehm, are you going to add ChargeID? Also are you going to make test files?

**Comment by AsaNehm** [comment]
Test files as in just running some files with it and telling you where to find them? Sure can do. Any files in particular that you want to have?
With the ChargeID I'm not entirely sure if I have to add it to this branch as it will get merged onto the main branch where the charge is already implemented... But will try my best

**Comment by AsaNehm** [comment]
Antineutrino.0_1715654453 test file available in /exp/dune/app/users/pnehm/dune-tms/antineutrino.0_1715654453.edep_TMS_RecoCandidates_Hough_Cluster1.root

**Comment by AsaNehm** [comment]
This should take care of the TMS_Charge problem

**Review by jdkio — APPROVED** [review]
Looks good

**Review by LiamOS — APPROVED** [review]
Have reviewed as much as I can for now, am merging to enable easier testing and further validation against the Kalman code.

**Comment by AsaNehm** [comment]
Conflicts should be resolved. I also took out the changes that I made to merge it with the Kalman filter, so this shouldn't be merged in already

**Pull request merged**
