### PR TITLE
Change to alternate method of finding x,y,z of bar

### PR DESCRIPTION
**Pull request by jdkio**
There was a previous version but that didn't seem to work based on the comments. I was able to verify that this version works

### CODE REVIEW

**Comment by jdkio** [comment]
I've added @AsaNehm, idk how this affects the downstream reco code. The x,y,z hit position correspond to the exact center of each bar according to the geometry. Are there downstream components that are affected? I put an example file run with this code here:
`/pnfs/dune/persistent/users/kleykamp/test_files/2024-04-09_kleykamp_bar_position_fix.root`

**Review by AsaNehm — COMMENTED** [review]
Could you explain a bit more what is changing? I'm not understanding what the effect is entirely (sry)

**Comment by jdkio** [comment]
That's okay! The TMS_Bar code has code to find x,y,z of a hit. That's supposed to be the location of the bar because we can't measure where within a bar the hit was. I checked and the method I use gives the right values.  There was another bit of code that used translations. I just checked that and it gives the same values. I was under the impression that the x,y,z values were not being filled correctly when I wrote this. So I guess this update isn't strictly neccessary, but maybe a bit neater

**Review by LiamOS — APPROVED** [review]
Looks sane and may help with more generalised geometries.

**Pull request merged**
