### PR TITLE
126 need to add charge id into the reconstruction code

### PR DESCRIPTION
**Pull request by AsaNehm**
This copies/moves the charge ID code from Xiaoyan directly into the reconstruction (pattern recognition) and makes it available as a property of the 3D tracks

### CODE REVIEW

**Comment by jdkio** [comment]
Do you want to add it as a branch in the TreeWriter so it's saved?

**Comment by AsaNehm** [comment]
> Do you want to add it as a branch in the TreeWriter so it's saved?

That's a really good suggestion. I completely forgot about that. Will add it in

**Comment by AsaNehm** [comment]
Xiaoyan gave his ok. Jeffrey asked for validation plots

**Review by jdkio — APPROVED** [review]
Looks good

**Comment by xiaoyan1997** [comment]
i tested the branch on 3 samples, worked well.

**Review by xiaoyan1997 — APPROVED** [review]

**Pull request merged**
