### PR TITLE
Fixed overlay issue by moving hits outside event.Primary loop. Added …

### PR DESCRIPTION
**Pull request by jdkio**
…reco effects section. Also saving timing info for tracks

### CODE REVIEW

**Review by ast0815 — COMMENTED** [review]
I don't have the capacity at the moment to check the logic of the changes or to test them. The code looks clean, but you introduce commented-out code in a couple of places. I think that should be avoided or it should be accompanied with a comment what those lines are used for and when one should uncomment them. Otherwise we just get commented-out code that no one dares to remove because no one knows what it is for, i.e. clutter. It is kinda obvious for debug output to stdout, but there are some other blocks of code that are less intuitive.

I also added Liam as reviewer since he is the package manager now and should give the final blessing.

**Comment by jdkio** [comment]
Thanks for the suggestions. I removed all the comment blocks I could find.

**Comment by jdkio** [comment]
Yeah that's an error. I'm not sure how that happened. You can remove it. Thanks

**Review by LiamOS — CHANGES_REQUESTED** [review]
It turns out that I can't delete this file from the commit with the web interface at least, presumably as it's a binary; if it's not too much work could you add a commit that deletes the file? Then I can merge.

**Comment by ast0815** [comment]
It would be better to rebase so that file is not part of the commit history at all. Otherwise it will still get downloaded with every "clone". Though it does not matter if you use "squash" to merge everything in the end and then delete this branch.

**Comment by jdkio** [comment]
I removed src/stbdA9YY via rebase.

**Review by LiamOS — APPROVED** [review]

**Comment by LiamOS** [comment]
Squashed and merged, apologies for the delay!

**Pull request merged**
